//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCSCarousel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCSCarousel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1924 by 768 pixels.
        /// </summary>
        internal static string _1024by768 {
            get {
                return ResourceManager.GetString("1024by768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280 by 1024 pixels.
        /// </summary>
        internal static string _1280by1024 {
            get {
                return ResourceManager.GetString("1280by1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280 by 720 pixels.
        /// </summary>
        internal static string _1280by720 {
            get {
                return ResourceManager.GetString("1280by720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280 by 768 pixels.
        /// </summary>
        internal static string _1280by768 {
            get {
                return ResourceManager.GetString("1280by768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280 by 800 pixels.
        /// </summary>
        internal static string _1280by800 {
            get {
                return ResourceManager.GetString("1280by800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1366 by 768 pixels.
        /// </summary>
        internal static string _1366by768 {
            get {
                return ResourceManager.GetString("1366by768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1400 by 1050 pixels.
        /// </summary>
        internal static string _1400by1050 {
            get {
                return ResourceManager.GetString("1400by1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1440 by 900 pixels.
        /// </summary>
        internal static string _1440by900 {
            get {
                return ResourceManager.GetString("1440by900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1600 by 1200 pixels.
        /// </summary>
        internal static string _1600by1200 {
            get {
                return ResourceManager.GetString("1600by1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1680 by 1050 pixels.
        /// </summary>
        internal static string _1680by1050 {
            get {
                return ResourceManager.GetString("1680by1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1920 by 1080 pixels.
        /// </summary>
        internal static string _1920by1080 {
            get {
                return ResourceManager.GetString("1920by1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1920 by 1200 pixels.
        /// </summary>
        internal static string _1920by1200 {
            get {
                return ResourceManager.GetString("1920by1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2560 by 1440 pixels.
        /// </summary>
        internal static string _2560by1440 {
            get {
                return ResourceManager.GetString("2560by1440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3440 by 1440.
        /// </summary>
        internal static string _3440by1440 {
            get {
                return ResourceManager.GetString("3440by1440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 640 by 480 pixels.
        /// </summary>
        internal static string _640by480 {
            get {
                return ResourceManager.GetString("640by480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800 by 600 pixels.
        /// </summary>
        internal static string _800by600 {
            get {
                return ResourceManager.GetString("800by600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brower version must be set.
        /// </summary>
        internal static string BrowserSetup {
            get {
                return ResourceManager.GetString("BrowserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling refresh.
        /// </summary>
        internal static string CancellingRefresh {
            get {
                return ResourceManager.GetString("CancellingRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current default user ({0}).
        /// </summary>
        internal static string ClearDefaultUserTitle {
            get {
                return ResourceManager.GetString("ClearDefaultUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compare object is not an instance of the CloudHostedInstance class.
        /// </summary>
        internal static string CloudHostedInstance {
            get {
                return ResourceManager.GetString("CloudHostedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Hosted.
        /// </summary>
        internal static string CloudHostedMenu {
            get {
                return ResourceManager.GetString("CloudHostedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare object RDPTerminal is null.
        /// </summary>
        internal static string CompareObjIsNull {
            get {
                return ResourceManager.GetString("CompareObjIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm action.
        /// </summary>
        internal static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deployment of package {0}, the environment will be unavailable during the deploy and it will take some time to finish..
        /// </summary>
        internal static string ConfirmDeployPackage {
            get {
                return ResourceManager.GetString("ConfirmDeployPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you log off, all locally saved information about your projects and instances will be deleted. You will need to refresh data from LCS.
        ///
        ///Application will close.
        ///
        ///Do you want to proceed?.
        /// </summary>
        internal static string ConfirmLogOut {
            get {
                return ResourceManager.GetString("ConfirmLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you wish to start the instance {0}.
        /// </summary>
        internal static string ConfirmStartInstance {
            get {
                return ResourceManager.GetString("ConfirmStartInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you wish to stop the instance {0}.
        /// </summary>
        internal static string ConfirmStopInstance {
            get {
                return ResourceManager.GetString("ConfirmStopInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials list is not valid, ensure that the list is not null, wrong use of function: RDPConnectionDetailsViewModel(List&lt;RDPConnectionDetails&gt; rdpList).
        /// </summary>
        internal static string CredentialsListIsNull {
            get {
                return ResourceManager.GetString("CredentialsListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current active project : {0}.
        /// </summary>
        internal static string CurrentProjectName {
            get {
                return ResourceManager.GetString("CurrentProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching available packages for environment: 
        ///Environment Id: {0}
        ///Display Name: {1}.
        /// </summary>
        internal static string FetchingPackages {
            get {
                return ResourceManager.GetString("FetchingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both name and IP address is required for a new rule, press Cancel to close, OK to re-enter the correct values..
        /// </summary>
        internal static string FirewallRuleNotCorrect {
            get {
                return ResourceManager.GetString("FirewallRuleNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Cache: In progress{0}Fetching Cloud hosted VM&apos;s: In progress{1}Fetching MS Hosted VM&apos;s: In progress.
        /// </summary>
        internal static string InitRefresh {
            get {
                return ResourceManager.GetString("InitRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress....
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login to LCS again to access all functions.
        /// </summary>
        internal static string LimitedSession {
            get {
                return ResourceManager.GetString("LimitedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged in to LCS.
        /// </summary>
        internal static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in status.
        /// </summary>
        internal static string LoggInStatus {
            get {
                return ResourceManager.GetString("LoggInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Hosted.
        /// </summary>
        internal static string MSHosteMenu {
            get {
                return ResourceManager.GetString("MSHosteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My RDP {0}.
        /// </summary>
        internal static string MyRDPTitle {
            get {
                return ResourceManager.GetString("MyRDPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the default user when you start your VM.
        /// </summary>
        internal static string NoDefaultUser {
            get {
                return ResourceManager.GetString("NoDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - No project selected.
        /// </summary>
        internal static string NoProjectSelected {
            get {
                return ResourceManager.GetString("NoProjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pick a project to access it&apos;s resources.
        /// </summary>
        internal static string NoProjectSelectedInformation {
            get {
                return ResourceManager.GetString("NoProjectSelectedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the user you wish to use to sign in with.
        /// </summary>
        internal static string NoRDPUserSelected {
            get {
                return ResourceManager.GetString("NoRDPUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options valid for the refresh is selected, cancelling the refresh.
        /// </summary>
        internal static string NoRefreshOptionsSelected {
            get {
                return ResourceManager.GetString("NoRefreshOptionsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in to LCS, do you wish to login now?.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log in to LCS before you can use this application.
        /// </summary>
        internal static string NotSignedIn {
            get {
                return ResourceManager.GetString("NotSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI can&apos;t be null.
        /// </summary>
        internal static string NullURI {
            get {
                return ResourceManager.GetString("NullURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compare object is not an instance of the RDPTerminal class.
        /// </summary>
        internal static string ObjIsNotRDPTerminal {
            get {
                return ResourceManager.GetString("ObjIsNotRDPTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Cache: {0}  
        ///Fetching Cloud hosted VM&apos;s: {1}
        ///Fetching MS Hosted VM&apos;s: {2}
        ///Clearing credentials Cloud Hosted: {3}
        ///Clearing credentials MS Hosted: {4}.
        /// </summary>
        internal static string RefreshProgress {
            get {
                return ResourceManager.GetString("RefreshProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the firewall rule {0}? Press OK to confirm removal.
        /// </summary>
        internal static string RemoveFirewallRule {
            get {
                return ResourceManager.GetString("RemoveFirewallRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this program as Admin the first time to register the correct browser version.
        /// </summary>
        internal static string RunAsAdminOnce {
            get {
                return ResourceManager.GetString("RunAsAdminOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current personal VM is {0}.
        /// </summary>
        internal static string SelectedRDPSession {
            get {
                return ResourceManager.GetString("SelectedRDPSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only select one user to sign in with.
        /// </summary>
        internal static string SelectRDPUserOnlyOneSelected {
            get {
                return ResourceManager.GetString("SelectRDPUserOnlyOneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select RDP User.
        /// </summary>
        internal static string SelectRDPUserTitle {
            get {
                return ResourceManager.GetString("SelectRDPUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is logged out from LCS, log in again.
        /// </summary>
        internal static string SessionEnded {
            get {
                return ResourceManager.GetString("SessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie valid to :  {0}.
        /// </summary>
        internal static string SessionTime {
            get {
                return ResourceManager.GetString("SessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
    }
}
